# DO NOT CHANGE the "init" and "install" sections below

image: Visual Studio 2015

environment:
  NOT_CRAN: true
  USE_RTOOLS: true
  PATH: "%PATH%;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0;C:\\MinGW\\msys\\1.0\\bin"
  matrix:
#    - PYTHON: "C:\\Python27"
#      RETICULATE_PYTHON: "C:\\Python27"
#      MINICONDA: C:\Miniconda2
    - PYTHON: "C:\\Python35"
      RETICULATE_PYTHON: "C:\\Python35"
      MINICONDA: C:\Miniconda3
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - PYTHON: "C:\\Python36"
      RETICULATE_PYTHON: "C:\\Python36"
      MINICONDA: C:\Miniconda3
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - PYTHON: "C:\\Python37"
      RETICULATE_PYTHON: "C:\\Python37"
      MINICONDA: C:\Miniconda3
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"
    - PYTHON: "C:\\Python34"
      RETICULATE_PYTHON: "C:\\Python34"
      MINICONDA: C:\Miniconda3
      CONDA_INSTALL_LOCN: "C:\\Miniconda34-x64"

matrix:
  fast_finish: true

# Download script file from GitHub
init:
  - ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install: 
  - set PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\scripts;%PATH%;
  - conda config --set always_yes yes --set changeps1 no 
  - conda update -q conda 
  - conda info -a 
  - conda config --add channels bashtage 
  - conda install -y -c conda-forge umap-learn 
  - conda create -y -q -n r-test -c conda-forge umap-learn numpy python=%PYTHON_VERSION%
  - conda init powershell
  - conda activate r-reticulate
  - pip install --user umap-learn
  - ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - 
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install setuptools numpy umap-learn"
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
